### ISSUE TITLE
Alterar dados para aceitar multiplos speakers

### ISSUE THREAD

**Issue by claudiosanches** [wpbrasil/slides#11]
Seguindo esta conversa: https://github.com/wpbrasil/slides/pull/9#issuecomment-140205678

> Na verdade o `speaker` deve ser um array/dicionario `speakers` e então adicionar cada `speaker` dentro. Esse seria o melhor padrão.

**Comment by bordoni** [comment]
Sim, eu vou mudar essa estrutura. Provavel que na quarta que consiga pegar para fazer.

Exemplo:

```
    - speakers: 
            - "Rafael Funchal"
            - "bordoni"
      url: "http://slides.com/bordoni/participar-comunidade-wordpress/"
      title: "Faça parte da comunidade WordPress"
      video:
```
