### ISSUE TITLE
Add Link dos Vídeos das palestras

### ISSUE THREAD

**Issue by theandersonn** [wpbrasil/slides#4]
Vamos inserir além dos slides o link das palestras tb?

**Comment by RafaelFunchal** [comment]
Podemos inserir, mas precisaríamos mudar como estamos inserindo.
- Palestrante - Palestra
  - [slide](#)
  - [video](#)

O que acha desse formato?

**Comment by theandersonn** [comment]
Pô acho legal, porque vai ficar no mesmo escopo e facilitará que encontremos essas informações futuramente.
Vou inserir os links dos vídeos do RJ.

**Comment by deblynprado** [comment]
Podia criar um arquivo por ano pra cada localidade.

Dentro dele dava pra fazer

```
- name: nome do meetup
  date: dia em que foi feito DD/MM/AAA
  slides: link pros slides
  video: link pro video
  - speakers:
    name: nome do palestrante
    profile: link pro wp.org
```

assim dá pra fazer um foreach por cada ano e popular as páginas

**Comment by RafaelFunchal** [comment]
Curti pra caramba essa ideia hein, @deblynprado 

Manda PR disso ai, Chezuiz

**Comment by leobaiano** [comment]
+1 para a estrutura do @deblynprado, a mesma pode ser aplicada nos WordCamps também.

**Comment by RafaelFunchal** [comment]
Essa p_ _ _ é tua, aspira

**Comment by deblynprado** [comment]
hahaha suave, vou fazer aqui ;)

**Comment by theandersonn** [comment]
Tem que pensar numa maneira que facilite a inclusão de conteúdo. Pensando nos users que não dominam a ferramenta.

**Comment by deblynprado** [comment]
eu acho que essa é a forma mais fácil até pra quem não domina... o cara só vai precisar digitar essas informações e mandar o pull.

Nada mais além disso.

**Comment by theandersonn** [comment]
Tá falado :)

**Comment by deblynprado** [comment]
menino @bordoni foi mais rápido hahahaha

**Comment by bordoni** [comment]
:wink:  #5

**Comment by theandersonn** [comment]
@bordoni Com a mudança como ficou o esquema para inserir os slides para os Meetups?

**Comment by RafaelFunchal** [comment]
É igual adicionar os vídeos e slides dos WordCamps, só muda o `type`.

Dando exemplo do Rio de Janeiro, precisará abrir o arquivo `/_data/places/rj.yml` e adicionar o meetup assim:

```
- type: meetup
  date: YYYY-MM-DD
  url: url-do-meetup
  slides:
    - speaker:
      url:
      title:
      video:
```
